<?php include 'db_connect.php' ?>
<?php
$query = "SELECT * from tb_data WHERE user_id = {$_SESSION['login_id']} ORDER BY id DESC";
$result = mysqli_query($conn, $query);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="card card-outline card-primary">
			<div class="card-header">
				<h3 class="card-title text-capitalize font-weight-bold">
					Maintenance Report List (<?= mysqli_num_rows($result) ?>)
				</h3>
				<div class="card-tools">
					<ul class="pagination pagination-sm m-0 float-right">
						<li class="page-item">
							<a class="btn btn-block btn-sm btn-default btn-flat border-primary new_request" href="javascript:void(0)"><i class="fa fa-plus"></i> New Request</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="card-body">
				<table class="table tabe-hover table-bordered report_list">
					<thead>
						<tr>
							<!-- <th scope="col">#</th> -->
							<th scope="col">Section</th>
							<!-- <th scope="col">Description</th> -->
							<th scope="col">Action Taken</th>
							<th scope="col">Remarks</th>
							<th scope="col">Evaluation Status</th>
							<!-- <th scope="col">Date Created</th> -->
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						<?php while ($row = mysqli_fetch_array($result)) : ?>
							<tr>
								<!-- <td class="text-center"><?php echo $row['id'] ?></td> -->
								<td><?php echo substr($row['languages'], 0, -1) ?></td>
								<!-- <td class="text-center"><?php echo $row['description'] ?></td> -->
								<td class="text-center"><?php echo date('F j, Y, g:i a', strtotime($row['date'])); ?></td>
								<td class="text-center">
									<?php if ($row['status'] == 1) : ?>
										<span class="badge badge-success">Accomplished</span>
									<?php else : ?>
										<span class="badge badge-warning">Under Process</span>
									<?php endif; ?>
								</td>
								<td class="text-center">
									<?php if ($row['f_status'] == 1) : ?>
										<span class="badge badge-success">Approved</span>
									<?php else : ?>
										<span class="badge badge-warning">Pending</span>
									<?php endif; ?>
								</td>
								<!-- <td class="text-center"><?php echo $row['date'] ?></td> -->
								<td class="text-center">
									<div class="btn-group">
										<button class="btn btn-sm btn-info view_report" type="button" data-id="<?php echo $row['id'] ?>">
											<i class="fa fa-eye"></i>
										</button>
										<button class="btn btn-sm btn-primary edit_report" type="button" data-id="<?php echo $row['id'] ?>">
											<i class="fa fa-edit"></i>
										</button>
										<button class="btn btn-sm btn-danger delete_report" type="button" data-id="<?php echo $row['id'] ?>">
											<i class="fa fa-trash"></i>
										</button>
									</div>
								</td>
							</tr>
						<?php endwhile; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('.report_list').dataTable({
			dom: 'Bfrtip',
			buttons: [
				'excel', 'pdf', {
					extend: 'print',
					text: 'Print',
					autoPrint: true,
					title: '',
					messageTop: '<header style="display: flex; justify-content: space-between; align-items: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/CTU_new_logo.png/1200px-CTU_new_logo.png" alt="CTU Logo" style="width: 100px; height: 100px;" /><p style="text-align: center;"> Republic of the Philippines <br> CEBU TECHNOLOGICAL UNIVERSITY <br> TUBURAN CAMPUS <br> Brgy. 8 Poblacion, Tuburan, Cebu <br> Tel. No. (032) 463-9350 </p><img src="https://upload.wikimedia.org/wikipedia/en/thumb/4/49/Seal_of_ASEAN.svg/1200px-Seal_of_ASEAN.svg.png" alt="ASEAN Logo" style="width: 100px; height: 100px;" />',
					messageBottom: 'This document is generated by the system and does not require signature.',
					customize: function(win) {
						$(win.document.body)
							.css('font-size', '10pt')
							.prepend(
								'<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/CTU_new_logo.png/1200px-CTU_new_logo.png" style="position:absolute; top:0; left:0; opacity:0.1;" />'
							);

						$(win.document.body).find('table')
							.addClass('compact')
							.css('font-size', 'inherit');
					}
				}
			]
		})
		$('.new_request').click(function() {
			uni_modal("New Request for Maintenance", "<?= $_SESSION['login_view_folder'] ?>manage_report.php")
		})
		$('.view_report').click(function() {
			uni_modal("Maintenance Report Details", "<?php echo $_SESSION['login_view_folder'] ?>view_report.php?id=" + $(this).attr('data-id'))
		})
		$('.edit_report').click(function() {
			uni_modal("Edit Maintenance Report", "<?php echo $_SESSION['login_view_folder'] ?>manage_report.php?id=" + $(this).attr('data-id'))
		})
		$('.delete_report').click(function() {
			_conf("Are you sure to delete this report?", "delete_report", [$(this).attr('data-id')])
		})
	})

	function delete_report($id) {
		start_load()
		$.ajax({
			url: 'ajax.php?action=delete_report',
			method: 'POST',
			data: {
				id: $id
			},
			success: function(resp) {
				if (resp == 1) {
					alert_toast("Data successfully deleted", 'success')
					setTimeout(function() {
						location.reload()
					}, 1500)
				}
			}
		})
	}
</script>